services:
  zpe-systems-http:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: zpe-systems-http
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      zpe-systems-mysql:
        condition: service_healthy
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 512M

  zpe-systems-mysql:
    image: mysql:8
    container_name: zpe-systems-mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 2
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
    ports:
        - "3306:3306"
    volumes:
        - storage:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '2'
          memory: 1024M

volumes:
  storage:

networks:
    default:
        name: go-skeleton-network
