definitions:
  go-skeleton_internal_application_services.Error:
    properties:
      Error:
        type: string
      Message: {}
      Status:
        type: integer
    type: object
  go-skeleton_internal_application_services_enforce.Data:
    properties:
      Method:
        type: string
      Resource:
        type: string
      UserId:
        type: string
    type: object
  go-skeleton_internal_application_services_enforce.Response:
    properties:
      Allowed:
        type: boolean
    type: object
  go-skeleton_internal_application_services_login.Data:
    properties:
      Email:
        type: string
      Password:
        type: string
    type: object
  go-skeleton_internal_application_services_login.Response:
    properties:
      AccessToken:
        type: string
    type: object
  go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Data:
    properties:
      Actions:
        items:
          type: string
        type: array
      Resource:
        type: string
      Role:
        type: string
    type: object
  go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Response:
    properties:
      Result:
        type: string
    type: object
  go-skeleton_internal_application_services_roles_LIST.Response:
    properties:
      Roles:
        items:
          type: string
        type: array
    type: object
  go-skeleton_internal_application_services_roles_SET_ROLE_TO_USER.Data:
    properties:
      RolesName:
        type: string
      UserId:
        type: string
    type: object
  go-skeleton_internal_application_services_users_CREATE.Data:
    properties:
      Email:
        type: string
      Id:
        type: string
      Name:
        type: string
      Password:
        type: string
      Roles:
        items:
          type: string
        type: array
    required:
    - Email
    - Name
    - Password
    - Roles
    type: object
  go-skeleton_internal_application_services_users_CREATE.Response:
    properties:
      Created:
        type: boolean
    type: object
  go-skeleton_internal_application_services_users_DELETE.Response:
    properties:
      Message:
        type: string
    type: object
  go-skeleton_internal_application_services_users_EDIT.Data:
    properties:
      Email:
        type: string
      Name:
        type: string
    type: object
  go-skeleton_internal_application_services_users_EDIT.Response:
    properties:
      Data:
        $ref: '#/definitions/go-skeleton_internal_application_services_users_EDIT.Data'
    type: object
  go-skeleton_internal_application_services_users_GET.Response:
    properties:
      Data:
        $ref: '#/definitions/go-skeleton_internal_application_services_users_GET.UserResponse'
    type: object
  go-skeleton_internal_application_services_users_GET.UserResponse:
    properties:
      Email:
        type: string
      Id:
        type: string
      Name:
        type: string
      Roles:
        items:
          type: string
        type: array
    type: object
  go-skeleton_internal_application_services_users_LIST.DataResponse:
    properties:
      Email:
        type: string
      Id:
        type: string
      Name:
        type: string
      Roles:
        items:
          type: string
        type: array
    type: object
  go-skeleton_internal_application_services_users_LIST.Response:
    properties:
      CurrentPage:
        type: integer
      Data:
        items:
          $ref: '#/definitions/go-skeleton_internal_application_services_users_LIST.DataResponse'
        type: array
      TotalPages:
        type: integer
    type: object
info:
  contact: {}
  description: This is the Zord backend server.
  title: Swagger Zord API
  version: "1.0"
paths:
  /enforce:
    get:
      consumes:
      - application/json
      parameters:
      - description: body model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-skeleton_internal_application_services_enforce.Data'
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_enforce.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Enforce
      tags:
      - Enforce
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-skeleton_internal_application_services_login.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_login.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Login
      tags:
      - Login
  /roles:
    get:
      consumes:
      - application/json
      parameters:
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_roles_LIST.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Get Roles
      tags:
      - Roles
  /roles/{role}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: Role Name
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Roles
      tags:
      - Roles
  /roles/add_resource_permission:
    post:
      consumes:
      - application/json
      parameters:
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: body model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Roles
      tags:
      - Roles
  /roles/deleteFromUser/{role}/{userId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: Role Name
        in: path
        name: role
        required: true
        type: string
      - description: User id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Roles
      tags:
      - Roles
  /roles/deletePermission/{role}/{resource}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: Role Name
        in: path
        name: role
        required: true
        type: string
      - description: Resource Name
        in: path
        name: resource
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Roles
      tags:
      - Roles
  /roles/setToUser:
    post:
      consumes:
      - application/json
      parameters:
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: body model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-skeleton_internal_application_services_roles_SET_ROLE_TO_USER.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_roles_ADD_RESOURCE_PERMISSION_TO_ROLE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Roles
      tags:
      - Roles
  /users:
    get:
      consumes:
      - application/json
      parameters:
      - description: valid int
        in: query
        name: page
        required: true
        type: integer
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_users_LIST.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: List Users
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: body model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-skeleton_internal_application_services_users_CREATE.Data'
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_users_CREATE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Create Users
      tags:
      - Users
  /users/{user_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Users ID
        in: path
        name: users_id
        required: true
        type: string
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_users_DELETE.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Delete Users
      tags:
      - Users
  /users/{users_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Users ID
        in: path
        name: users_id
        required: true
        type: string
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_users_GET.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Get a Users
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: Users ID
        in: path
        name: users_id
        required: true
        type: string
      - description: body model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-skeleton_internal_application_services_users_EDIT.Data'
      - description: JWT Auth
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services_users_EDIT.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-skeleton_internal_application_services.Error'
      summary: Edit Users
      tags:
      - Users
swagger: "2.0"
